### ISSUE TITLE
Gemini prompt structure to define action plan from goal of "help the environment"

### ISSUE THREAD

**Issue by ogallagher** [hoanghm/Proact#8]
Design prompt templates and sequencing to accept an initial goal and related user profile information, and break it down into an action plan. The plan is essentially a sequence of subgoals/milestones/chapters, and the choice of subgoals informed by both Gemini and the user.

**Comment by ogallagher** [comment]
I know that we're currently focusing on goals like "help the environment", but whenever possible I would like to work toward supporting all sorts of goals. Considering how to support various kinds of goals in Notion - [Support various kinds of goals](https://www.notion.so/Prompt-Templates-f3a7462d1067433d9695612b9b3c40d7?pvs=4#57d43ba0a8584bc4b6b8c78453cf719b).

**Comment by hoanghm** [comment]
@ogallagher There is something similar to "supporting all goals" that already exists and is pretty good and it's called AutoGPT. 

We can attempt something like that if we have time later, but focusing specifically on the environment at least for now like you said is a good choice, since there will always be a trade-off between generality and quality.

**Comment by ogallagher** [comment]
Even if we don't support generic goals other than "help the environment", I don't think we should close this issue yet.

**Comment by hoanghm** [comment]
No longer relevant, close to create a fresh ticket that is more related to the title.

**Comment by hoanghm** [comment]
No longer relevant, close to create a fresh ticket that is more related to the title.
